version: '3'
services:
  cockroach:
    network_mode: host
    build: .
    ports:
    - "8000:8000"
    volumes:
    - .:/app/
  cockroachnginx:
    network_mode: host
    build: nginx/.  
    ports:
    - "80:80"
